In [79]:
!pip install --upgrade pip
!pip install -U pandas matplotlib nltk spacy

Requirement already satisfied: pip in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (26.0.1)
Requirement already satisfied: pandas in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: matplotlib in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: nltk in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (3.9.3)
Requirement already satisfied: spacy in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (3.8.11)
Requirement already satisfied: numpy>=2.3.3 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from nltk) (4.67.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from spacy) (82.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: six>=1.5 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/kevin/Documents/ai-engineer/nlp/.venv/lib/python3.14/site-packages (from jinja2->spacy) (3.0.3)

In [76]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# import spacy
import pandas as pd
import re
import matplotlib.pyplot as plt

In [67]:
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /Users/kevin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/kevin/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/kevin/nltk_data...

True

In [48]:
bbc_data = pd.read_csv("bbc_news.csv")

In [49]:
bbc_data.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [50]:
bbc_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   str
 3   pubDate      1000 non-null   str
 4   guid         1000 non-null   str
 5   link         1000 non-null   str
 6   description  1000 non-null   str
dtypes: int64(2), str(5)
memory usage: 54.8 KB

In [54]:
titles = pd.DataFrame(bbc_data['title'])
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [ ]:
titles['lowercase'] = titles['title'].str.lower()
titles.head()

,title,lowercase
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [59]:
en_stopwords = stopwords.words('english')
titles['no_stopwords'] = titles['lowercase'].apply(lambda x: ' '.join([word for word in x.split(' ') if word not in (en_stopwords)]))
titles.head()

,title,lowercase,no_stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

In [60]:
titles['no_stopwords_no_punc'] = titles.apply(lambda x: re.sub(r"([^\w\s])", "", x["no_stopwords"]), axis=1)
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punc
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

In [65]:
titles['tokens_raw'] = titles.apply(lambda x: word_tokenize(x['title']), axis=1)
titles['tokens_clean'] = titles.apply(lambda x: word_tokenize(x['no_stopwords_no_punc']), axis=1)
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punc,tokens_raw,tokens_clean
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco..."

In [71]:
lemmatizer = WordNetLemmatizer()
titles['tokens_clean_lemmatized'] = titles['tokens_clean'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punc,tokens_raw,tokens_clean,tokens_clean_lemmatized
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]"

In [73]:
tokens_raw_list = sum(titles['tokens_raw'], [])
tokens_raw_list

['Can',
 'I',
 'refuse',
 'to',
 'work',
 '?',
 "'Liz",
 'Truss',
 'the',
 'Brief',
 '?',
 "'",
 'World',
 'reacts',
 'to',
 'UK',
 'political',
 'turmoil',
 'Rationing',
 'energy',
 'is',
 'nothing',
 'new',
 'for',
 'off-grid',
 'community',
 'The',
 'hunt',
 'for',
 'superyachts',
 'of',
 'sanctioned',
 'Russian',
 'oligarchs',
 'Platinum',
 'Jubilee',
 ':',
 '70',
 'years',
 'of',
 'the',
 'Queen',
 'in',
 '70',
 'seconds',
 'Red',
 'Bull',
 'found',
 'guilty',
 'of',
 'breaking',
 'Formula',
 '1',
 "'s",
 'budget',
 'cap',
 'World',
 'Triathlon',
 'Championship',
 'Series',
 ':',
 'Flora',
 'Duffy',
 'beats',
 'Georgia',
 'Taylor-Brown',
 'to',
 'women',
 "'s",
 'title',
 'Terry',
 'Hall',
 ':',
 'Coventry',
 'scooter',
 'ride-out',
 'pays',
 'tribute',
 'to',
 'singer',
 'Post',
 'Office',
 'and',
 'Fujitsu',
 'to',
 'face',
 'inquiry',
 'over',
 'Horizon',
 'scandal',
 "'Pavement",
 'parking',
 'frightens',
 'me',
 "'",
 'UK',
 'interest',
 'rates',
 ':',
 'How',
 'will',
 'the',
 'rise',
 'affect',
 'you',
 'and',
 'how',
 'high',
 'could',
 'it',
 'go',
 '?',
 'They',
 'stayed',
 'for',
 'the',
 'storm',
 '-',
 'what',
 'happens',
 'now',
 '?',
 'Six',
 'Nations',
 ':',
 'Can',
 'Scotland',
 "'s",
 'best',
 'since',
 "'99",
 'beat',
 'best',
 'Ireland',
 'ever',
 '?',
 'How',
 'long',
 'can',
 'Liz',
 'Truss',
 'survive',
 'as',
 'prime',
 'minister',
 '?',
 'Platinum',
 'Jubilee',
 ':',
 'Beacons',
 'light',
 'across',
 'the',
 'globe',
 'to',
 'celebrate',
 'Queen',
 "'s",
 'reign',
 'Top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 'by',
 '5',
 '%',
 'in',
 'England',
 'Russians',
 'said',
 'they',
 '’',
 'd',
 'take',
 'my',
 'baby',
 ':',
 'A',
 'medic',
 '’',
 's',
 'story',
 'Week',
 'in',
 'pictures',
 ':',
 '11-17',
 'June',
 '2022',
 'Xi',
 'Jinping',
 'in',
 'Hong',
 'Kong',
 ':',
 'Tight',
 'security',
 'as',
 'city',
 'marks',
 '25',
 'years',
 'of',
 'handover',
 'Rescues',
 'carried',
 'out',
 'in',
 'silence',
 'to',
 'listen',
 'for',
 'sounds',
 'of',
 'life',
 'Nick',
 'Pope',
 ':',
 'Newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'How',
 'China',
 'plans',
 'to',
 'become',
 'the',
 'next',
 'big',
 'space',
 'power',
 'Barcelona',
 'thrash',
 'leaders',
 'Real',
 'Madrid',
 'in',
 'famous',
 'Clasico',
 'win',
 'Kuenssberg',
 ':',
 'The',
 'Budget',
 'can',
 'not',
 'mask',
 'big',
 'changes',
 'to',
 'our',
 'economy',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'What',
 'we',
 'know',
 'about',
 'her',
 'disappearance',
 'Cost',
 'of',
 'living',
 ':',
 'Can',
 'Christmas',
 'lights',
 'displays',
 'survive',
 'the',
 'energy',
 'crisis',
 '?',
 'The',
 '100-year-old',
 'Edinburgh',
 'man',
 'still',
 'working',
 'three',
 'days',
 'a',
 'week',
 'Freya',
 'the',
 '600kg',
 'walrus',
 'causes',
 'a',
 'stir',
 'in',
 'Norway',
 'How',
 'can',
 'I',
 'offer',
 'a',
 'UK',
 'home',
 'to',
 'Ukrainian',
 'refugees',
 '?',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'Former',
 'police',
 'boss',
 'says',
 'criticism',
 'is',
 'unfair',
 'Don',
 'Bolduc',
 ':',
 'Democrats',
 'elevated',
 'this',
 'Republican',
 '.',
 'Will',
 'it',
 'backfire',
 '?',
 'Some',
 'strike',
 'action',
 'cancelled',
 'after',
 'the',
 'Queen',
 "'s",
 'death',
 'The',
 'neighbourhood',
 'leading',
 'a',
 'green',
 'energy',
 'revolution',
 'Men',
 "'s",
 'U17',
 'European',
 'Championship',
 ':',
 'Dutch',
 '17-year-old',
 'Isaac',
 'Babadi',
 'scores',
 'Panenka',
 'penalty',
 'Amtrak',
 'derailment',
 ':',
 'Three',
 'killed',
 'in',
 'Missouri',
 'after',
 'train',
 'hits',
 'truck',
 'Energy',
 'price',
 'cap',
 ':',
 'Rising',
 'bills',
 '-',
 'four',
 'discounts',
 'and',
 'payments',
 'that',
 'could',
 'help',
 'you',
 'Environment',
 ':',
 'Are',
 'mushroom',
 'boards',
 'the',
 'future',
 'of',
 'surfing',
 '?',
 'Flying',
 'boats',
 'and',
 'other',
 'tech',
 'for',
 'cleaner',
 'shipping',
 'Scottish',
 'football',
 'to',
 'ban',
 'heading',
 'the',
 'day',
 'before',
 'and',
 'after',
 'matches',
 'Chris',
 'Eubank',
 'Jr',
 'v',
 'Liam',
 'Smith',
 ':',
 'What',
 'next',
 'for',
 'boxing',
 'after',
 "'unacceptable",
 "'",
 'taunts',
 '?',
 'The',
 'town',
 'destroyed',
 'to',
 'make',
 'way',
 'for',
 'a',
 'whites-only',
 'suburb',
 'Ukraine',
 'war',
 ':',
 'A',
 'village',
 'celebrates',
 'Russian',
 'retreat',
 'Root',
 'hits',
 'ton',
 'as',
 'England',
 'take',
 'command',
 'against',
 'West',
 'Indies',
 'Heineken',
 'Champions',
 'Cup',
 ':',
 'Leicester',
 '16-6',
 'Edinburgh',
 '-',
 'Jasper',
 'Wiese',
 'try',
 'sends',
 'Tigers',
 'into',
 'last',
 'eight',
 'World',
 'Cup',
 '2022',
 ':',
 'Bellingham',
 ',',
 'Gakpo',
 ',',
 'Fernandez',
 'and',
 'other',
 'breakout',
 'stars',
 'Briton',
 'Jack',
 'Fenton',
 'killed',
 'in',
 'Greek',
 'helicopter',
 'accident',
 'Emotional',
 'Sue',
 'Barker',
 'gets',
 'Centre',
 'Court',
 'ovation',
 'Ukrainian',
 'skating',
 'sisters',
 'back',
 'to',
 "'doing",
 'what',
 'they',
 'love',
 "'",
 'England',
 'v',
 'India',
 ':',
 'Edgbaston',
 'officials',
 'investigate',
 'crowd',
 'racism',
 'at',
 'Test',
 'Newspaper',
 'headlines',
 ':',
 'Rwanda',
 'plan',
 "'will",
 'fail',
 "'",
 'and',
 "'SAS",
 'train',
 'Kyiv',
 'forces',
 "'",
 'My',
 'Name',
 'Is',
 'Leon',
 ':',
 'Sir',
 'Lenny',
 'Henry',
 'brings',
 "'moving",
 "'",
 'adoption',
 'story',
 'to',
 'screen',
 'Big',
 'Brother',
 'star',
 'Glyn',
 'Wise',
 'plans',
 'to',
 'be',
 'priest',
 'Ministers',
 'asleep',
 'at',
 'the',
 'wheel',
 'over',
 'dentist',
 'shortages',
 ',',
 'say',
 'Lib',
 'Dems',
 'Chris',
 'Kaba',
 ':',
 'Met',
 'suspends',
 'officer',
 'who',
 'shot',
 'dead',
 'unarmed',
 'man',
 'World',
 'Cup',
 '2022',
 ':',
 'What',
 'we',
 'learned',
 'from',
 'a',
 'group',
 'stage',
 'that',
 'saw',
 'record',
 'number',
 'of',
 'upsets',
 'James',
 'Webb',
 ':',
 'Nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'pictures',
 'Constitution',
 'Hill',
 ':',
 'Cheltenham',
 'Champion',
 'Hurdle',
 'winner',
 "'the",
 'horse',
 'of',
 'a',
 'generation',
 "'",
 'At',
 'least',
 'one',
 'victim',
 'could',
 'have',
 'survived',
 'arena',
 'bomb',
 '-',
 'inquiry',
 'Gareth',
 'Bale',
 ':',
 'Wales',
 'captain',
 'retires',
 'from',
 'football',
 'aged',
 '33',
 'Ukraine',
 'war',
 ':',
 'Silent',
 'streets',
 'in',
 'wiped',
 'out',
 'Donetsk',
 'town',
 'World',
 'Cup',
 '2022',
 ':',
 'Vittorio',
 'Pozzo',
 "'s",
 'legacy',
 'and',
 'a',
 'record',
 'that',
 'might',
 'finally',
 'be',
 'under',
 'threat',
 'Train',
 'strikes',
 ':',
 'Workers',
 'vote',
 'on',
 'further',
 'six',
 'months',
 'of',
 'walkouts',
 'Eidevall',
 "'100",
 '%',
 'sure',
 "'",
 'Arsenal',
 'will',
 'advance',
 'after',
 'first-leg',
 'draw',
 'Ukraine',
 'war',
 ':',
 'Returning',
 'to',
 'the',
 'place',
 'my',
 'father',
 'was',
 'killed',
 'Furniture',
 'firm',
 'Made',
 'collapse',
 ':',
 'Customers',
 'in',
 'the',
 'dark',
 'over',
 'refunds',
 'Widow',
 'of',
 'US',
 'Capitol',
 'riot',
 'officer',
 'on',
 "'stigma",
 "'",
 'of',
 'his',
 'death',
 'NHS',
 'reaches',
 'deal',
 'for',
 'life-saving',
 'breast-cancer',
 'drug',
 'Giant',
 'ceramic',
 'sculpture',
 'by',
 'Sandy',
 'Brown',
 'has',
 'been',
 'unveiled',
 'in',
 'Cornwall',
 'CEO',
 'Secrets',
 ':',
 'How',
 'one',
 'company',
 'attracts',
 'more',
 'men',
 'Boris',
 'Becker',
 ':',
 'How',
 'a',
 'tennis',
 'superstar',
 'crashed',
 'to',
 'earth',
 'Turkish',
 'mine',
 'explosion',
 'kills',
 '25',
 'and',
 'leaves',
 'dozens',
 'trapped',
 'Indian',
 'Wells',
 ':',
 'Andy',
 'Murray',
 ',',
 'Emma',
 'Raducanu',
 'and',
 'Jack',
 'Draper',
 'win',
 'to',
 'reach',
 'third',
 'round',
 'World',
 'Athletics',
 'Championships',
 ':',
 'GB',
 "'s",
 'Keely',
 'Hodgkinson',
 'narrowly',
 'misses',
 'out',
 'on',
 'gold',
 'in',
 'dramatic',
 '800m',
 'NHS',
 'crisis',
 ':',
 'The',
 'medics',
 'trying',
 'to',
 'fix',
 'the',
 'health',
 'service',
 'How',
 'did',
 'jet',
 'crash',
 'into',
 'a',
 'block',
 'of',
 'flats',
 'in',
 'Russia',
 '?',
 'Prince',
 'Harry',
 'and',
 'Meghan',
 ':',
 'Where',
 'do',
 'they',
 'get',
 'their',
 'money',
 '?',
 'Chelsea',
 '4-2',
 'Man',
 'Utd',
 ':',
 'Chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'WSL',
 'title',
 'Tory',
 'leadership',
 ':',
 'I',
 "'d",
 'rather',
 'lose',
 'doing',
 'right',
 'thing',
 ',',
 'says',
 'Sunak',
 'Omagh',
 'police',
 'shooting',
 ':',
 'Four',
 'men',
 'released',
 'over',
 'John',
 'Caldwell',
 'attack',
 'Northern',
 'Ireland',
 '1-0',
 'Italy',
 ':',
 'Sarah',
 'McFadden',
 'scores',
 'famous',
 'winner',
 'in',
 'Belfast',
 'Actress',
 'Clara',
 'Darcy',
 ':',
 'Why',
 'I',
 "'m",
 'starring',
 'in',
 'a',
 'play',
 'about',
 'my',
 'brain',
 'tumour',
 'Bridgerton',
 ':',
 'South',
 'Asian',
 'faces',
 'on',
 'TV',
 "'makes",
 'me',
 'happy',
 "'",
 'Prince',
 'Harry',
 'remembers',
 'Queen',
 'Elizabeth',
 'II',
 "'s",
 'infectious',
 'smile',
 'Millions',
 'to',
 'receive',
 'latest',
 'cost-of-living',
 'payment',
 'Joe',
 'Biden',
 'heads',
 'to',
 'Middle',
 'East',
 'amid',
 'faltering',
 'US',
 'sway',
 'NHS',
 ':',
 'Public',
 'satisfaction',
 'with',
 'health',
 'service',
 'drops',
 'to',
 'record',
 'low',
 'Why',
 'have',
 "n't",
 'we',
 'seen',
 'any',
 'major',
 'winter',
 'storms',
 '?',
 'The',
 'Papers',
 ':',
 'Lions',
 "'bare",
 'teeth',
 "'",
 'and',
 'Starmer',
 "'s",
 'migration',
 'policy',
 'Afghanistan',
 'pupils',
 'in',
 'fear',
 'after',
 'spate',
 'of',
 'Islamic',
 'State',
 'attacks',
 'Princess',
 'of',
 'Wales',
 'Kate',
 'pays',
 'tribute',
 'to',
 'Queen',
 'Elizabeth',
 'at',
 'carol',
 'service',
 'Emma',
 'Raducanu',
 ...]

In [74]:
tokens_clean_list = sum(titles['tokens_clean'], [])
tokens_clean_list

['refuse',
 'work',
 'liz',
 'truss',
 'brief',
 'world',
 'reacts',
 'uk',
 'political',
 'turmoil',
 'rationing',
 'energy',
 'nothing',
 'new',
 'offgrid',
 'community',
 'hunt',
 'superyachts',
 'sanctioned',
 'russian',
 'oligarchs',
 'platinum',
 'jubilee',
 '70',
 'years',
 'queen',
 '70',
 'seconds',
 'red',
 'bull',
 'found',
 'guilty',
 'breaking',
 'formula',
 '1s',
 'budget',
 'cap',
 'world',
 'triathlon',
 'championship',
 'series',
 'flora',
 'duffy',
 'beats',
 'georgia',
 'taylorbrown',
 'womens',
 'title',
 'terry',
 'hall',
 'coventry',
 'scooter',
 'rideout',
 'pays',
 'tribute',
 'singer',
 'post',
 'office',
 'fujitsu',
 'face',
 'inquiry',
 'horizon',
 'scandal',
 'pavement',
 'parking',
 'frightens',
 'me',
 'uk',
 'interest',
 'rates',
 'rise',
 'affect',
 'high',
 'could',
 'go',
 'stayed',
 'storm',
 'happens',
 'now',
 'six',
 'nations',
 'scotlands',
 'best',
 'since',
 '99',
 'beat',
 'best',
 'ireland',
 'ever',
 'long',
 'liz',
 'truss',
 'survive',
 'prime',
 'minister',
 'platinum',
 'jubilee',
 'beacons',
 'light',
 'across',
 'globe',
 'celebrate',
 'queens',
 'reign',
 'top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 '5',
 'england',
 'russians',
 'said',
 'theyd',
 'take',
 'baby',
 'medics',
 'story',
 'week',
 'pictures',
 '1117',
 'june',
 '2022',
 'xi',
 'jinping',
 'hong',
 'kong',
 'tight',
 'security',
 'city',
 'marks',
 '25',
 'years',
 'handover',
 'rescues',
 'carried',
 'silence',
 'listen',
 'sounds',
 'life',
 'nick',
 'pope',
 'newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'china',
 'plans',
 'become',
 'next',
 'big',
 'space',
 'power',
 'barcelona',
 'thrash',
 'leaders',
 'real',
 'madrid',
 'famous',
 'clasico',
 'win',
 'kuenssberg',
 'budget',
 'can',
 'not',
 'mask',
 'big',
 'changes',
 'economy',
 'nicola',
 'bulley',
 'search',
 'know',
 'disappearance',
 'cost',
 'living',
 'christmas',
 'lights',
 'displays',
 'survive',
 'energy',
 'crisis',
 '100yearold',
 'edinburgh',
 'man',
 'still',
 'working',
 'three',
 'days',
 'week',
 'freya',
 '600kg',
 'walrus',
 'causes',
 'stir',
 'norway',
 'offer',
 'uk',
 'home',
 'ukrainian',
 'refugees',
 'nicola',
 'bulley',
 'search',
 'former',
 'police',
 'boss',
 'says',
 'criticism',
 'unfair',
 'bolduc',
 'democrats',
 'elevated',
 'republican',
 'backfire',
 'strike',
 'action',
 'cancelled',
 'queens',
 'death',
 'neighbourhood',
 'leading',
 'green',
 'energy',
 'revolution',
 'mens',
 'u17',
 'european',
 'championship',
 'dutch',
 '17yearold',
 'isaac',
 'babadi',
 'scores',
 'panenka',
 'penalty',
 'amtrak',
 'derailment',
 'three',
 'killed',
 'missouri',
 'train',
 'hits',
 'truck',
 'energy',
 'price',
 'cap',
 'rising',
 'bills',
 'four',
 'discounts',
 'payments',
 'could',
 'help',
 'environment',
 'mushroom',
 'boards',
 'future',
 'surfing',
 'flying',
 'boats',
 'tech',
 'cleaner',
 'shipping',
 'scottish',
 'football',
 'ban',
 'heading',
 'day',
 'matches',
 'chris',
 'eubank',
 'jr',
 'v',
 'liam',
 'smith',
 'next',
 'boxing',
 'unacceptable',
 'taunts',
 'town',
 'destroyed',
 'make',
 'way',
 'whitesonly',
 'suburb',
 'ukraine',
 'war',
 'village',
 'celebrates',
 'russian',
 'retreat',
 'root',
 'hits',
 'ton',
 'england',
 'take',
 'command',
 'west',
 'indies',
 'heineken',
 'champions',
 'cup',
 'leicester',
 '166',
 'edinburgh',
 'jasper',
 'wiese',
 'try',
 'sends',
 'tigers',
 'last',
 'eight',
 'world',
 'cup',
 '2022',
 'bellingham',
 'gakpo',
 'fernandez',
 'breakout',
 'stars',
 'briton',
 'jack',
 'fenton',
 'killed',
 'greek',
 'helicopter',
 'accident',
 'emotional',
 'sue',
 'barker',
 'gets',
 'centre',
 'court',
 'ovation',
 'ukrainian',
 'skating',
 'sisters',
 'back',
 'doing',
 'love',
 'england',
 'v',
 'india',
 'edgbaston',
 'officials',
 'investigate',
 'crowd',
 'racism',
 'test',
 'newspaper',
 'headlines',
 'rwanda',
 'plan',
 'will',
 'fail',
 'sas',
 'train',
 'kyiv',
 'forces',
 'name',
 'leon',
 'sir',
 'lenny',
 'henry',
 'brings',
 'moving',
 'adoption',
 'story',
 'screen',
 'big',
 'brother',
 'star',
 'glyn',
 'wise',
 'plans',
 'priest',
 'ministers',
 'asleep',
 'wheel',
 'dentist',
 'shortages',
 'say',
 'lib',
 'dems',
 'chris',
 'kaba',
 'met',
 'suspends',
 'officer',
 'shot',
 'dead',
 'unarmed',
 'man',
 'world',
 'cup',
 '2022',
 'learned',
 'group',
 'stage',
 'saw',
 'record',
 'number',
 'upsets',
 'james',
 'webb',
 'nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'pictures',
 'constitution',
 'hill',
 'cheltenham',
 'champion',
 'hurdle',
 'winner',
 'the',
 'horse',
 'generation',
 'least',
 'one',
 'victim',
 'could',
 'survived',
 'arena',
 'bomb',
 'inquiry',
 'gareth',
 'bale',
 'wales',
 'captain',
 'retires',
 'football',
 'aged',
 '33',
 'ukraine',
 'war',
 'silent',
 'streets',
 'wiped',
 'donetsk',
 'town',
 'world',
 'cup',
 '2022',
 'vittorio',
 'pozzos',
 'legacy',
 'record',
 'might',
 'finally',
 'threat',
 'train',
 'strikes',
 'workers',
 'vote',
 'six',
 'months',
 'walkouts',
 'eidevall',
 '100',
 'sure',
 'arsenal',
 'advance',
 'firstleg',
 'draw',
 'ukraine',
 'war',
 'returning',
 'place',
 'father',
 'killed',
 'furniture',
 'firm',
 'made',
 'collapse',
 'customers',
 'dark',
 'refunds',
 'widow',
 'us',
 'capitol',
 'riot',
 'officer',
 'stigma',
 'death',
 'nhs',
 'reaches',
 'deal',
 'lifesaving',
 'breastcancer',
 'drug',
 'giant',
 'ceramic',
 'sculpture',
 'sandy',
 'brown',
 'unveiled',
 'cornwall',
 'ceo',
 'secrets',
 'one',
 'company',
 'attracts',
 'men',
 'boris',
 'becker',
 'tennis',
 'superstar',
 'crashed',
 'earth',
 'turkish',
 'mine',
 'explosion',
 'kills',
 '25',
 'leaves',
 'dozens',
 'trapped',
 'indian',
 'wells',
 'andy',
 'murray',
 'emma',
 'raducanu',
 'jack',
 'draper',
 'win',
 'reach',
 'third',
 'round',
 'world',
 'athletics',
 'championships',
 'gbs',
 'keely',
 'hodgkinson',
 'narrowly',
 'misses',
 'gold',
 'dramatic',
 '800m',
 'nhs',
 'crisis',
 'medics',
 'trying',
 'fix',
 'health',
 'service',
 'jet',
 'crash',
 'block',
 'flats',
 'russia',
 'prince',
 'harry',
 'meghan',
 'get',
 'money',
 'chelsea',
 '42',
 'man',
 'utd',
 'chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'wsl',
 'title',
 'tory',
 'leadership',
 'rather',
 'lose',
 'right',
 'thing',
 'says',
 'sunak',
 'omagh',
 'police',
 'shooting',
 'four',
 'men',
 'released',
 'john',
 'caldwell',
 'attack',
 'northern',
 'ireland',
 '10',
 'italy',
 'sarah',
 'mcfadden',
 'scores',
 'famous',
 'winner',
 'belfast',
 'actress',
 'clara',
 'darcy',
 'starring',
 'play',
 'brain',
 'tumour',
 'bridgerton',
 'south',
 'asian',
 'faces',
 'tv',
 'makes',
 'happy',
 'prince',
 'harry',
 'remembers',
 'queen',
 'elizabeth',
 'iis',
 'infectious',
 'smile',
 'millions',
 'receive',
 'latest',
 'costofliving',
 'payment',
 'joe',
 'biden',
 'heads',
 'middle',
 'east',
 'amid',
 'faltering',
 'us',
 'sway',
 'nhs',
 'public',
 'satisfaction',
 'health',
 'service',
 'drops',
 'record',
 'low',
 'seen',
 'major',
 'winter',
 'storms',
 'papers',
 'lions',
 'bare',
 'teeth',
 'starmers',
 'migration',
 'policy',
 'afghanistan',
 'pupils',
 'fear',
 'spate',
 'islamic',
 'state',
 'attacks',
 'princess',
 'wales',
 'kate',
 'pays',
 'tribute',
 'queen',
 'elizabeth',
 'carol',
 'service',
 'emma',
 'raducanu',
 'us',
 'open',
 'champion',
 'discusses',
 'tough',
 'split',
 'coach',
 'torben',
 'beltz',
 'oxford',
 'united',
 '03',
 'arsenal',
 'eddie',
 'nketiah',
 'scores',
 'twice',
 'gunners',
 'progress',
 'ukraine',
 'roundup',
 'putin',
 'defends',
 'necessary',
 'invasion',
 'kyiv',
 'averts',
 'cyberattack',
 'ni',
 'protocol',
 'uk',
 'eu',
 'reach',
 'agreement',
 'trade',
 'data',
 'sharing',
 'super',
 'mario',
 'bros',
 'movie',
 'jack',
 'black',
 'rise',
 'game',
 'adaptations',
 'fourtime',
 'slam',
 'champion',
 'osaka',
 'announces',
 'pregnancy',
 'mcdonalds',
 'cocacola',
 'boycott',
 'calls',
 'grow',
 'russia',
 'womens',
 'footballer',
 'year',
 'contender',
 'sam',
 'kerr',
 'war',
 'ukraine',
 'vladimir',
 'putin',
 'trained',
 'fighters',
 'africa',
 'ryanairs',
 'michael',
 'oleary',
 'wants',
 'practical',
 'immigration',
 'approach',
 'i',
 'planned',
 'end',
 'life',
 '16',
 'still',
 'here',
 'englands',
 '14',
 'men',
 'whipped',
 'twickenham',
 'crowd',
 'stirring',
 'display',
 'open',
 'rory',
 'mcilroy',
 'viktor',
 'hovland',
 'share',
 'lead',
 'st',
 'andrews',
 'third',
 'round',
 'real',
 'madrid',
 '20',
 'eintracht',
 'frankfurt',
 'karim',
 'benzema',
 'scores',
 '324th',
 'goal',
 'real',
 'super',
 'cup',
 'win',
 'papers',
 'boris',
 'dossier',
 'judges',
 'to',
 'back',
 'down',
 'rwanda',
 'queen',
 'pulls',
 'attending',
 'commonwealth',
 'service',
 'mosque',
 'fire',
 'suspect',
 'arrested',
 'second',
 'attack',
 'world',
 'cup',
 '2022',
 'belgium',
 'drop',
 'love',
 'away',
 'shirts',
 'qatar',
 'uks',
 'living',
 'covid',
 'plans',
 'sohos',
 'streets',
 'turned',
 'new',
 'london',
 'art',
 'gallery',
 'papers',
 'cruise',
 'ships',
 'house',
 'migrants',
 'new',
 'nhs',
 'cash',
 'pay',
 'gap',
 'bosses',
 'staff',
 'widen',
 'think',
 'tank',
 'local',
 'elections',
 'children',
 'urge',
 'action',
 'save',
 'wildlife',
 'climate',
 'change',
 'uk',
 'track',
 'meet',
 'targets',
 'trump',
 'investigation',
 'empty',
 'folders',
 'marked',
 'classified',
 'found',
 'maralago',
 'jim',
 'ratcliffe',
 'man',
 'bidding',
 'man',
 'utd',
 'shropshire',
 'baby',
 'deaths',
 'parents',
 'whose',
 'lives',
 'changed',
 'forever',
 'bus',
 'journeys',
 'taken',
 'since',
 '2',
 'fare',
 'cap',
 'says',
 'watchdog',
 'mexico',
 'kidnapping',
 'twisted',
 'moral',
 'code',
 'explains',
 'cartels',
 'apology',
 'rail',
 'fares',
 'england',
 'rise',
 'inflation',
 'rate',
 'ministers',
 'say',
 'taliban',
 'schools',
 'uturn',
 'a',
 'devastating',
 'day',
 'afghan',
 'girls',
 'malala',
 'yousafzai',
 'met',
 'police',
 'next',
 'force',
 'casey',
 'review',
 'ukraine',
 'war',
 'kherson',
 'mariupol',
 'key',
 'russian',
 'success',
 'heineken',
 'champions',
 'cup',
 'premiership',
 'cap',
 'hinders',
 'english',
 'teams',
 'alex',
 'sanderson',
 'ukraine',
 'war',
 'protester',
 'exposes',
 'cracks',
 'kremlins',
 'war',
 'message',
 'liz',
 'truss',
 'vows',
 'match',
 'ukraine',
 'military',
 'support',
 'politics',
 'returns',
 'wales',
 'population',
 'hits',
 'new',
 'high',
 'growth',
 'lowest',
 'many',
 'ukrainians',
 'fled',
 'homes',
 'gone',
 'deloitte',
 'report',
 'european',
 'football',
 'made',
 'significant',
 'recovery',
 'covid',
 'pandemic',
 'nigeria',
 'floods',
 'overwhelming',
 'disaster',
 'leaves',
 '600',
 'people',
 'dead',
 'wimbledon',
 'emma',
 'raducanu',
 'andy',
 'murray',
 'set',
 'centre',
 'court',
 'day',
 'one',
 'journey',
 'site',
 'nord',
 ...]

In [77]:
nlp = spacy.load("en_core_web_sm")

NameError: name 'spacy' is not defined

In [78]:
spacy_doc = nlp(''.join(tokens_raw_list))

NameError: name 'nlp' is not defined

In [81]:
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

for token in spacy_doc:
    # print(token)
    pos_df = pd.concat([pos_df,
                        pd.DataFrame.from_records([{'token': token, 'pos_tag': token.pos_}])], ignore_index=True)

NameError: name 'spacy_doc' is not defined