In [32]:
!uv pip install ipykernel pandas numpy matplotlib seaborn plotly scikit-learn --quiet

In [33]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [34]:
features, target = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [35]:
features.shape, target.shape

((100, 2), (100,))

In [36]:
df = pd.DataFrame({'feature1': features[:,0], 'feature2': features[:,1], 'target': target})
df.sample(5)

    feature1  feature2     target
69  0.344614  0.176065 -32.776956
33 -1.103381  0.033858  42.421115
54  0.400809 -1.739708  34.755501
95 -0.295088  0.936710  30.344046
9   1.048167 -0.446336  76.179553

In [37]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target', opacity=0.1)

fig.show()

In [38]:
from sklearn.model_selection import train_test_split
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.2, random_state=3)

In [39]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(features_train, target_train)

LinearRegression()

In [40]:
target_pred = lr.predict(features_test)

In [41]:
print("MAE", mean_absolute_error(target_test, target_pred))
print("MSE", mean_squared_error(target_test, target_pred))
print("R2 score", r2_score(target_test, target_pred))

MAE 29.36137594852055
MSE 1310.7314833512305
R2 score 0.23647783447817539

In [42]:
m = lr.coef_
m

array([25.43629112,  6.42954979])

In [43]:
b = lr.intercept_
b

np.float64(-8.926687336561377)

In [44]:
df.head(5)

   feature1  feature2      target
0 -0.614541 -0.757109  -79.139330
1  0.692245 -0.044992  -20.213785
2  1.476201 -1.880432    4.460084
3  0.435347  1.022019 -133.077063
4  2.696630 -0.711639   25.900025

In [45]:
# y = mx + b


m * 9.580000 + b

array([234.75298162,  52.66839967])

In [46]:
m * 100 + b

array([2534.70242491,  634.02829189])